services:
  - type: web
    name: meditation-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: COHERE_API_KEY
        sync: false
